### ISSUE TITLE
Warning messages displayed for Click UI Command

### ISSUE THREAD

**Issue by anithae6589** [gopyyn/Salad#26]
While using to click the displayed text in the test, the test is passed but the warning message is displayed for all click events. 

Could this is removed to avoid confusion.

Eg: click("displayed text on UI") or click ("button name in UI") is used and the following warning message is displayed.

Apr 24, 2024 1:47:58 PM com.gopyyn.salad.core.SaladCommands getClickableChild
SEVERE: no clickable child element
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":".//button|.//input|.//select|.//a|.//textarea|.//fieldset"}
  (Session info: chrome=124.0.6367.61)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [644dffe4c78dbefca9b70e1fe3cb74d4, findChildElement {using=xpath, id=f.700C54AB52C15F8A09F4543FC1993002.d.9E06F2008BBF93EE265E6E56CD6D2DCF.e.8, value=.//button|.//input|.//select|.//a|.//textarea|.//fieldset}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 124.0.6367.61, chrome: {chromedriverVersion: 124.0.6367.78 (a087f2dd364d..., userDataDir: C:\Users\MCHATT~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:60048}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:60048/devtoo..., se:cdpVersion: 124.0.6367.61, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 644dffe4c78dbefca9b70e1fe3cb74d4
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)

**Comment by gopyyn** [comment]
Thanks for bringing this up. I will work over the weekend and create a new release version

**Comment by gopyyn** [comment]
Change the log level to trace. Please use the new version 1.0.9
